import Head from "next/head";
import React from "react";
import Hero from "@/components/GeneratedTweets/Hero";
import CommunityTweets from "@/components/GeneratedTweets/CommunityTweets";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tweet GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <CommunityTweets />
      </div>
    </>
  );
}
